export const TYPES = {
  // GET_TICKETS: "GET_TICKETS",
  // CHANGE_PAGE: "CHANGE_PAGE",
  SORT_CITIES: "SORT_CITIES",
  FILTER_CITIES: "FILTER_CITIES",
  GET_OFFERS: "GET_OFFERS",
  GET_OFFER_DETAILS: "GET_OFFER_DETAILS",
  RESET_STATES: "RESET_STATES",
  POST_FLIGHT: "POST_FLIGHT",
  GET_FLIGHTS: "GET_FLIGHTS",
  GET_CITIES: "GET_CITIES",

  ADD_FAVORITE: "ADD_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE",

  GET_ITINERARIES: "GET_ITINERARIES",
  PUT_ITINERARY: "PUT_ITINERARY",
  DELETE_ITINERARY: "DELETE_ITINERARY",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  ADD_QUANTITY: "ADD_QUANTITY",
  LOAD_CURRENT_ITEM: "LOAD_CURRENT_ITEM",
  CALCULATE_TOTAL: "CALCULATE_TOTAL",
  IS_ON_SEARCH: "IS_ON_SEARCH",

  SIGN_UP:"SIGN_UP",
  SIGN_IN:"SIGN_IN",

};
