export const TYPES = {
  // GET_TICKETS: "GET_TICKETS",
  // CHANGE_PAGE: "CHANGE_PAGE",
  SORT_CITIES: "SORT_CITIES",
  FILTER_CITIES: "FILTER_CITIES",
  GET_OFFERS: "GET_OFFERS",
  GET_OFFER_DETAILS: "GET_OFFER_DETAILS",
  RESET_STATES: "RESET_STATES",
  GET_FLIGHTS: "GET_FLIGHTS",
  GET_CITIES: "GET_CITIES",
};
