export const TYPES = {
  GET_TICKETS: "GET_TICKETS",
  CHANGE_PAGE: "CHANGE_PAGE",
  SORT_CITIES: "SORT_CITIES",
  FILTER_CITIES: "FILTER_CITIES",
  GET_CITY: "GET_CITY",
  GET_CITY_DETAILS: "GET_CITY_DETAILS",
};
